### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by DrDinosaur** [ChrisTruncer/Hasher#3]
Hi, having some errors with NTLM.

http://pastebin.com/uJ2ppu5c

**Comment by DrDinosaur** [comment]
After setup script: 

Please provide the hash to use.
Hash: 19451f0ddda039cd6fb5cb8263aca3ef
Traceback (most recent call last):
  File "./Hasher.py", line 475, in <module>
    main()
  File "./Hasher.py", line 440, in main
    compareNTLM(hashchoice, stringprovided, mainhash)
  File "./Hasher.py", line 353, in compareNTLM
    verifiednt = hashes.nthash.verify(stringprovided, mainhash.split(":")[1])
IndexError: list index out of range

**Comment by ChrisTruncer** [comment]
Cool, thanks for letting me know.  I'll get looking into this now

**Comment by ChrisTruncer** [comment]
With NTLM, it needs the full hash (something like 01fc5a6be7bc6929aad3b435b51404ee:0cb6948805f797bf2a82807973b89537).  So with only half of it, it won't work currently.  If you need just NT, I can look into adding it.

**Comment by ChrisTruncer** [comment]
just let me know if you need/want anything added

**Comment by DrDinosaur** [comment]
I guess I'm just dumb :P. Maybe a message saying that the hash type is
wrong or you need to include more. Maybe a more graceful exit if something
goes wrong. Thanks.

**Comment by ChrisTruncer** [comment]
Yup, that should be added in now, so ideally it should be set
