### ISSUE TITLE
Special chars in password

### ISSUE THREAD

**Issue by xaitax** [ChrisTruncer/Hasher#5]
Hi,

seems hasher can't handle properly special chars. It always results in an error. Example:

✔ xaitax@w00t ~/tools/hasher master > ./Hasher.py --plaintext test!@# --hash-type all -G
bash: !@#: event not found

Same goes if I put them in " or '

Cheers.

**Comment by ChrisTruncer** [comment]
You need to escape the "!", bash is having a problem with it.  If you run the following command, it will work for you:

./Hasher.py --plaintext test\!@# --hash-type all -G

**Comment by ChrisTruncer** [comment]
Hope that helps!
